#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/asmvik/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    mouse_follows_focus          on             \
    focus_follows_mouse          off

yabai -m config                                 \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             first_child    \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        1.0            \
    window_opacity               off

yabai -m config                                 \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  4              \
    bottom_padding               4              \
    left_padding                 4              \
    right_padding                4              \
    window_gap                   5              \
    external_bar                 all:0:42       \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m space 1 --label 1
yabai -m space 2 --label 2
yabai -m space 3 --label 3
yabai -m space 4 --label 4
yabai -m space 5 --label 5
yabai -m space 6 --label 6
yabai -m space 7 --label 7
yabai -m space 8 --label 8
yabai -m space 9 --label 9
yabai -m space 10 --label 10

yabai -m rule --add app="^System Preferences$"    manage=off
yabai -m rule --add app="^System Settings$"       manage=off
yabai -m rule --add app="^Raycast$"               manage=off
yabai -m rule --add app="^Raycast Settings$"      manage=off
yabai -m rule --add app="^Finder$"                manage=off
yabai -m rule --add app="^Calendar$"              manage=off
yabai -m rule --add app="^TabTab$"                manage=off

yabai -m rule --add app="^Zen$"               space=^1
yabai -m rule --add app="^Helium$"            space=^1
yabai -m rule --add app="^Zed$"               space=^2
yabai -m rule --add app="^Cursor$"            space=^2
yabai -m rule --add app="^VSCodium$"          space=^2
yabai -m rule --add app="^Ghostty$"           space=^3
yabai -m rule --add app="^OrbStack$"          space=^3
yabai -m rule --add app="^Postman$"           space=^3
yabai -m rule --add app="^Warp$"              space=^3
yabai -m rule --add app="^Slack$"             space=^4
yabai -m rule --add app="^Discord$"           space=^4
yabai -m rule --add app="^Vesktop$"           space=^4
yabai -m rule --add app="^Zalo$"              space=^4
yabai -m rule --add app="^Microsoft Teams$"   space=^4
yabai -m rule --add app="^Facebook$"          space=^4
yabai -m rule --add app="^Obsidian$"          space=^5
yabai -m rule --add app="^Notion$"            space=^5
yabai -m rule --add app="^Claude$"            space=^6
yabai -m rule --add app="^Spotify$"           space=^8

yabai -m rule --apply

yabai -m signal --add app='^Ghostty$' event=window_created action='yabai -m space --layout bsp'
yabai -m signal --add app='^Ghostty$' event=window_destroyed action='yabai -m space --layout bsp'

echo "yabai configuration loaded.."
