#!/bin/bash

source "$CONFIG_DIR/colors.sh"
PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --bar position=bottom        \
                 height=37              \
                 topmost=window         \
                 padding_left=5         \
                 padding_right=5        \
                 color=$BG              \
                 corner_radius=12       \
                 y_offset=2             \
                 margin=4               \
                 shadow=on              \
                 font_smoothing=on      \
                 sticky=on

default=(
  padding_left=3
  padding_right=3
  icon.font="SFMono Nerd Font:Bold:14.0"
  label.font="SFMono Nerd Font:Regular:13.0"
  icon.color=$FG
  label.color=$FG
  icon.padding_left=6
  icon.padding_right=6
  label.padding_left=6
  label.padding_right=6
)
sketchybar --default "${default[@]}"

##### Spaces #####
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
for i in "${!SPACE_ICONS[@]}"
do
  sid=$(($i+1))
  space=(
    space=$sid
    icon="${SPACE_ICONS[i]}"
    icon.padding_left=10
    icon.padding_right=12
    icon.color=$GREY
    icon.highlight_color=$BR_RED
    padding_left=2
    padding_right=2
    label.font="sketchybar-app-font:Regular:16.0"
    label.padding_right=14
    label.y_offset=-1
    label.drawing=off
    label.background.height=26
    label.background.drawing=on
    label.background.color=$SURFACE_BORDER
    label.background.corner_radius=8
    script="$PLUGIN_DIR/space.sh"
  )
  sketchybar --add space space.$sid left          \
             --set space.$sid "${space[@]}"       \
             --subscribe space.$sid mouse.clicked
done

sketchybar --add bracket spaces '/space\..*/'                   \
           --set spaces background.color=$SURFACE               \
                        background.border_color=$SURFACE_BORDER \
                        background.border_width=2               \
                        background.corner_radius=8              \
                        background.height=29                    \
                        background.padding_left=8               \
                        background.padding_right=12             \
                        background.drawing=on

##### Space window watcher #####
sketchybar --add event windows_on_spaces                              \
           --add item space_windows left                              \
           --set space_windows drawing=off                            \
                               script="$PLUGIN_DIR/space_windows.sh"  \
           --subscribe space_windows space_change                     \
                                     windows_on_spaces                \
                                     front_app_switched

##### Front app #####
sketchybar --add item chevron left                                      \
           --set chevron icon="󰶻"                                       \
                         icon.font="SFMono Nerd Font:Bold:16.0"         \
                         icon.color=$GREY                               \
                         label.drawing=off                              \
                         padding_left=8                                 \
                         padding_right=0                                \
           --add item front_app left                                    \
           --set front_app icon.font="sketchybar-app-font:Regular:16.0" \
                           label.font="SFMono Nerd Font:Bold:14.0"      \
                           padding_left=0                               \
                           script="$PLUGIN_DIR/front_app.sh"            \
           --subscribe front_app front_app_switched

sketchybar --update
